name: 🚀 Feature Request
description: Suggest an idea, feature, or enhancement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an idea. It helps make viabl better.

        If you want to discuss viabl, or learn how others are using viabl, please
        join our [Discord](https://discord.gg/JyBMrk4G) server, where you can share your feedback.
  - type: textarea
    attributes:
      label: What is the problem this feature would solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the feature you are proposing to solve the problem?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What alternatives have you considered?